#!/bin/bash

if [[ -z $DOCKER ]]; then
    DOCKER=docker
fi

if (( $# != 3 )); then
    echo "usage: $0 id_file src_file dest_file"
    exit 1
fi

id_file=$1
src_file=$2
dest_file=$3

image=$($DOCKER create $(cat $id_file))
$DOCKER cp $image:$src_file $dest_file
$DOCKER rm -v $image
