#!/usr/bin/env perl
if (!$ENV{DID_EXEC} && $^X ne $ENV{SYSTEM_PERL}) {
    $ENV{DID_EXEC} = 1;
    exec($ENV{SYSTEM_PERL}, @ARGV);
}
use strict;
use warnings;

eval {
    require Digest::SHA;
    require Digest::MD5;
} or die "$^X is a broken perl install";

my $ver = $^V;
$ver =~ s/^v//;
exec('perl-build', qw(--noman -A ccflags=-fPIC -D useshrplib), $ver, "/opt/vanilla-perl");
