#!/bin/bash

set -e
wget $S3_BUCKET_URI/bmo/vendor.tar.gz -O /vendor.tar.gz
tar --transform 's/bmo\///' -zxvf /vendor.tar.gz
perl vendor/bin/carton install --cached --deployment
perl vendor/bin/carton update "$@"
package-bundle
